### ISSUE TITLE
Get setup with FOSSA and CodeCov

### ISSUE THREAD

**Issue by andorsk** [TBD54566975/incubation-wallet-rendering#5]
@ALRubinger would be great to add some FOSSA checks to this. Can you help set me up here? 

For CodeCov, just the key would be needed for now. Tests will come later, but just getting the admin stuff out of the way for now.

**Comment by andorsk** [comment]
Can you also confirm I'm good setting up a project for tracking this?

**Comment by ALRubinger** [comment]
@andorsk - We don't have a FOSSA account yet but I think it'd be great to use this project to trial their free offering. We've discussed things like this; could you outline the features you'd like?

* License checks?
* Dependency CVE alerts?
* What else?

If it's to trail FOSSA, +1 here and I'll set up a trial with them and we can enable it on this repo.

CodeCov - specifically what do you need from me here?

**Comment by andorsk** [comment]
There should be a CodeCov token I should be able to use. Also just wanted to make sure, pinged you on Discord, I'm good to go  to actually start merging things right?

**Comment by ALRubinger** [comment]
OK, cool! Until now we hadn't enabled CodeCov for the organization; as a trial I've set this up but we may look to organizationally assess how we want to handle code coverage and be intentional about selecting (a) provider(s). 

I've got a token if you need it, but per the docs:

```
*Not required if your repo is using GitHub Actions, Travic CI, CircleCI, AppVeyor, or Azure Pipelines.
```

Got your ping on Discord, answered there for anyone following along. Yep - assuming we're respecting license and CoC, repo is OPEN FOR BUSINESS and is yours to project lead!

**Comment by andorsk** [comment]
@ALRubinger there are Organizational Secrets that you can do rather than repo specific secrets. That might be the best way across org. 

Thanks so much for the help!

**Comment by andorsk** [comment]
#9 brings the FOSSA checks to life! Spun up a codecov issue to separate out concerns. #11. We can close this.
